create table `goods_base` (
	`id` bigint(20) unsigned not null auto_increment comment '商品Id --商品唯一标识',
	`title` varchar(20) not null default '' comment '商品标题',
	`sub_title` varchar(60) not null default '' comment '商品副标题 ',
	`des` varchar(225) not null default '' comment '悦选小编说',
	`shop_price` int(11) unsigned not null default '0' comment '商品售价',
	`origin_price` int(11) unsigned not null default '0' comment '商品原价',
	`cost` int(11) unsigned not null default '0' comment '商品成本价',
	`img` varchar(100) not null default '' comment '商品图片',
	`sale_num` int(11) unsigned not null default '0' comment '销量 --暂无统计',
	`stock_num` int(11) unsigned not null default '0' comment '库存',
	`is_on_sale` tinyint(3) unsigned not null default '0' comment '是否上架  0:下架 1:上架',
	`catagory1` int(11) unsigned not null default '0' comment '一级类目 0:类目未填写 1:食品',
	`catagory2` int(11) unsigned not null default '0' comment '二级类目 0:类目未填写 101:冲饮 102:保健品 103:糖巧点心 104:速食/调味品 105:厨具/餐具 106:零食 107:酒水 108:生鲜',
	`catagory3` int(11) unsigned not null default '0' comment '三级类目 ',
	`catagory4` int(11) unsigned not null default '0' comment '四级类目 ',
	`shop_id` bigint(20) unsigned not null default '0' comment '商户Id 暂无',
	`app_id` bigint(20) unsigned not null default '0' comment 'platform',
	`created` bigint(20) unsigned not null default '0',
	`updated` bigint(20) unsigned not null default '0',
 	`is_deleted` tinyint(3) unsigned not null default '0' comment '是否删除 0:未删除 1:已删除',
	PRIMARY key (`id`),
	key `idx_title_saleNum_updated` (`title` , `sale_num` ,`updated`),
  key `idx_catagory2_catagory3_catagory4` (`catagory2` , `catagory3` , `catagory4`),
	key `idx_catalog3_catalog4` (`catagory3` , `catagory4`	)
)engine=innodb default charset = utf8mb4 comment '新商品表' auto_increment = 100000